import os
import json
import asyncio
import logging
from pathlib import Path
import cloudinary
import cloudinary.uploader
from cloudinary.exceptions import Error as CloudinaryError
from youtube_search.config import settings

logger = logging.getLogger(__name__)

class AudioDownloader:
    def __init__(self):
            self.download_dir = Path(settings.DOWNLOAD_DIR)
                    self.download_dir.mkdir(parents=True, exist_ok=True)
                            
                                    # Load konfigurasi multiple Cloudinary dari Environment Variable (Format JSON)
                                            self.cloudinary_accounts = []
                                                    try:
                                                                accounts_json = os.getenv("CLOUDINARY_ACCOUNTS_JSON", "[]")
                                                                            self.cloudinary_accounts = json.loads(accounts_json)
                                                                                        logger.info(f"✅ Berhasil memuat {len(self.cloudinary_accounts)} konfigurasi Cloudinary.")
                                                                                                except json.JSONDecodeError:
                                                                                                            logger.error("❌ Format CLOUDINARY_ACCOUNTS_JSON tidak valid!")

                                                                                                                async def download_audio(self, video_id: str, title: str, duration: int = 0) -> dict:
                                                                                                                        # 1. FILTER DURASI (PENTING!)
                                                                                                                                max_duration = getattr(settings, 'MAX_VIDEO_DURATION', 420) # Default 7 menit (420 detik)
                                                                                                                                        if duration > 0 and duration > max_duration:
                                                                                                                                                    raise Exception(f"Durasi video ({duration} detik) melebihi batas maksimal {max_duration} detik.")

                                                                                                                                                            # Bersihkan judul agar aman untuk nama file / public_id di Cloudinary
                                                                                                                                                                    safe_title = "".join([c for c in title if c.isalpha() or c.isdigit() or c==' ']).rstrip()
                                                                                                                                                                            filename = f"{video_id}_{safe_title}" 
                                                                                                                                                                                    filepath = self.download_dir / f"{filename}.mp3"

                                                                                                                                                                                            # 2. Proses Download & Convert via yt-dlp
                                                                                                                                                                                                    bitrate = getattr(settings, 'AUDIO_BITRATE', 128)
                                                                                                                                                                                                            cmd = [
                                                                                                                                                                                                                        "yt-dlp", 
                                                                                                                                                                                                                                    "-x", 
                                                                                                                                                                                                                                                "--audio-format", "mp3",
                                                                                                                                                                                                                                                            "--audio-quality", f"{bitrate}K",
                                                                                                                                                                                                                                                                        "--match-filter", f"duration <= {max_duration}", # Double check filter di sisi yt-dlp
                                                                                                                                                                                                                                                                                    "-o", str(filepath),
                                                                                                                                                                                                                                                                                                f"https://www.youtube.com/watch?v={video_id}"
                                                                                                                                                                                                                                                                                                        ]

                                                                                                                                                                                                                                                                                                                logger.info(f"Memulai download audio untuk: {video_id}")
                                                                                                                                                                                                                                                                                                                        process = await asyncio.create_subprocess_exec(
                                                                                                                                                                                                                                                                                                                                    *cmd, stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.PIPE
                                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                                                                    stdout, stderr = await process.communicate()

                                                                                                                                                                                                                                                                                                                                                            if process.returncode != 0:
                                                                                                                                                                                                                                                                                                                                                                        error_msg = stderr.decode()
                                                                                                                                                                                                                                                                                                                                                                                    if "does not pass filter" in error_msg:
                                                                                                                                                                                                                                                                                                                                                                                                    raise Exception(f"Video ditolak: Durasi melebihi {max_duration} detik.")
                                                                                                                                                                                                                                                                                                                                                                                                                raise Exception(f"yt-dlp error: {error_msg}")

                                                                                                                                                                                                                                                                                                                                                                                                                        file_size = filepath.stat().st_size
                                                                                                                                                                                                                                                                                                                                                                                                                                logger.info(f"Download MP3 berhasil. Ukuran: {file_size} bytes")

                                                                                                                                                                                                                                                                                                                                                                                                                                        # 3. Proses Upload ke Cloudinary dengan Mekanisme Auto-Failover
                                                                                                                                                                                                                                                                                                                                                                                                                                                final_url = None
                                                                                                                                                                                                                                                                                                                                                                                                                                                        successful_account = None

                                                                                                                                                                                                                                                                                                                                                                                                                                                                for i, account in enumerate(self.cloudinary_accounts):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            try:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            logger.info(f"Mencoba upload ke Cloudinary Akun ke-{i+1} ({account.get('name', 'Unknown')})")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # Konfigurasi Cloudinary sementara untuk akun ini
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            cloudinary.config(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                cloud_name=account['cloud_name'],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    api_key=account['api_key'],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        api_secret=account['api_secret'],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            secure=True # Wajib True agar URL menggunakan https
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # Upload file 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # TRICK: resource_type="video" agar Cloudinary mengizinkannya di-streaming sebagai audio
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            response = cloudinary.uploader.upload(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                str(filepath),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    resource_type="video", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        public_id=filename,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            format="mp3",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                overwrite=True # Timpa jika file dengan nama sama sudah ada
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                final_url = response['secure_url']
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                successful_account = account.get('name', f'Akun-{i+1}')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                logger.info(f"✅ Upload BERHASIL ke {successful_account}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                break # Keluar dari loop, tidak perlu coba akun berikutnya

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            except CloudinaryError as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            logger.warning(f"❌ Upload ke akun ke-{i+1} GAGAL (Error: {str(e)}). Mencoba akun berikutnya...")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            continue
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        logger.warning(f"❌ Upload ke akun ke-{i+1} GAGAL (Exception: {str(e)}). Mencoba akun berikutnya...")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        continue

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # 4. Cleanup File Lokal & Return
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if final_url:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if filepath.exists():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    os.remove(filepath)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    logger.info("🗑️ File lokal di Render telah dihapus untuk menghemat storage.")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "video_id": video_id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "title": title,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "filename": f"{filename}.mp3",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "download_url": final_url,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "storage_source": "cloudinary",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "storage_account": successful_account,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "file_size": file_size
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                raise Exception("Gagal mengupload ke semua akun Cloudinary. Kemungkinan semua akun mencapai limit storage/bandwidth.")